services:
  pinto-db:
    image: postgres:16-alpine
    container_name: pinto-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinto
    ports:
      - "5434:5432"
    volumes:
      - pinto-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pinto-db-data:
